In [1]:
import numpy as np 
import math 
import matplotlib.pyplot as plt

In [130]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([400 , 300 , 150])
print(f"x = {x_train} , x.shape = {x_train.shape}")

x = [[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]] , x.shape = (3, 4)


In [167]:
m = x_train.shape[0]
n = x_train.shape[1]
alpha = 1e-7 * 2
iterations = 10000 
print("m =",m)
print("n =",n )
print(f"learning rate = {alpha}")

m = 3
n = 4
learning rate = 2e-07


In [168]:
w = np.zeros(n)
b = 0.43

In [169]:
def predict ( x, w , b ) :
    return np.dot(x , w ) + b 

In [170]:
def compute_cost(w , b, x_train, y_train) :
    cost = 0 
    for i in range (m) : 
        f = np.dot(x_train[i] , w ) + b  
        cost += (y_train[i] - f)**2 
        
    return cost/(2*m)   

In [171]:
def compute_gradient (w , b , x_train , y_train ) :
    dj_dw = np.zeros(n)
    dj_db = 0 
    for i in range(m) : 
        err = np.dot(w,x_train[i]) + b - y_train[i] 
        dj_dw = dj_dw + err*x_train[i]
        dj_db += err
    dj_dw /= m 
    dj_db /= m 

    return dj_dw , dj_db 
    
    


In [172]:
def gradient_descent (w , b, x_train , y_train , alpha  , iterations ) : 

    for i in range( iterations ) : 
        dj_dw , dj_db = compute_gradient (w , b , x_train , y_train ) 
        w -= alpha * dj_dw 
        b -= alpha * dj_db
        if (i % 500 == 0 ) : 
            print(f"current cost = {compute_cost(w,b,x_train,y_train)}     w= {w} b = {b}  ")
    return w , b             
            
        

In [173]:
w , b = gradient_descent(w,b,x_train , y_train , alpha , iterations)

current cost = 12479.733864433781     w= [9.28213360e-02 2.13046667e-04 7.65520000e-05 2.34656000e-03] b = 0.43005658066666663  
current cost = 156.29111282956717     w= [1.94424700e-01 1.66827197e-04 9.03654564e-04 3.65679035e-03] b = 0.4300597978281851  
current cost = 156.26911375278996     w= [ 1.94456400e-01 -1.13204587e-04  1.64914915e-03  2.40726635e-03] b = 0.4300013512399851  
current cost = 156.2473729875026     w= [ 0.19448783 -0.00039331  0.00239517  0.00116843] b = 0.429943281144655  
current cost = 156.22588598596207     w= [ 1.94518989e-01 -6.73473755e-04  3.14171087e-03 -5.98154073e-05] b = 0.429885584212103  
current cost = 156.20464828060048     w= [ 0.19454988 -0.00095371  0.00388877 -0.00127756] b = 0.4298282571417243  
current cost = 156.18365548261048     w= [ 0.19458051 -0.00123401  0.00463634 -0.0024849 ] b = 0.42977129666213576  
current cost = 156.1629032805561     w= [ 0.19461088 -0.00151438  0.00538441 -0.00368193] b = 0.4297146995309189  
current cost = 156

In [174]:
print(w)
print(b)

[ 0.19498285 -0.00516435  0.01515194 -0.01834308]
0.4290106813734115
