In [1]:
import numpy as np 
import math 
import matplotlib.pyplot as plt

In [2]:
x_train = np.array([[210, 5, 1, 45], [141, 3, 2, 40], [85, 2, 1, 35]])
y_train = np.array([400 , 300 , 150])
print(f"x = {x_train} , x.shape = {x_train.shape}")

x = [[210   5   1  45]
 [141   3   2  40]
 [ 85   2   1  35]] , x.shape = (3, 4)


In [11]:
m = x_train.shape[0]
n = x_train.shape[1]
alpha = 7e-5
iterations = 1000000
print("m =",m)
print("n =",n )
print(f"learning rate = {alpha}")

m = 3
n = 4
learning rate = 7e-05


In [12]:
w = np.ones(n)
b = 1

In [13]:
def predict ( x, w , b ) :
    return np.dot(x , w ) + b 

In [14]:
def compute_cost(w , b, x_train, y_train) :
    cost = 0 
    for i in range (m) : 
        f = np.dot(x_train[i] , w ) + b  
        cost += (y_train[i] - f)**2 
        
    return cost/(2*m)   

In [15]:
def compute_gradient (w , b , x_train , y_train ) :
    dj_dw = np.zeros(n)
    dj_db = 0 
    for i in range(m) : 
        err = np.dot(w,x_train[i]) + b - y_train[i] 
        dj_dw = dj_dw + err*x_train[i]
        dj_db += err
    dj_dw /= m 
    dj_db /= m 

    return dj_dw , dj_db 
    
    


In [16]:
def gradient_descent (w , b, x_train , y_train , alpha  , iterations ) : 

    for i in range( iterations ) : 
        dj_dw , dj_db = compute_gradient (w , b , x_train , y_train ) 
        w -= alpha * dj_dw 
        b -= alpha * dj_db
        if (i % 5000 == 0 ) : 
            print(f"current cost = {compute_cost(w,b,x_train,y_train)}     w= {w} b = {b}  ")
    return w , b             
            
        

In [17]:
w , b = gradient_descent(w,b,x_train , y_train , alpha , iterations)

current cost = 3303.9884472995177     w= [2.09953667 1.02522333 1.0091     1.2716    ] b = 1.0064633333333333  
current cost = 132.22550009932198     w= [ 1.99541585  0.08291342  3.64696569 -0.313799  ] b = 0.8999330049794213  
current cost = 112.16075784636557     w= [ 2.02912804 -0.79091149  6.14375805 -0.44570437] b = 0.8481651443961479  
current cost = 95.14076778852359     w= [ 2.0601772  -1.59571022  8.44332091 -0.56719013] b = 0.8004865903955499  
current cost = 80.703499772966     w= [ 2.08877369 -2.33693535 10.56123404 -0.67907934] b = 0.756574315753039  
current cost = 68.45703505443792     w= [ 2.11511125 -3.01960877 12.51184654 -0.78213007] b = 0.7161308101833219  
current cost = 58.06892714229419     w= [ 2.13936833 -3.64835567 14.30837401 -0.8770405 ] b = 0.6788820646768813  
current cost = 49.257177100580606     w= [ 2.16170926 -4.22743587 15.9629881  -0.96445366] b = 0.6445757150600848  
current cost = 41.782578313742896     w= [ 2.18228541 -4.76077269 17.48689901 -1.04

In [18]:
print(w)
print(b)

[  2.42218941 -10.97911915  35.25466893  -1.98363189]
0.24458688994352631
